version: '1'

services:
  mysql:
    container_name: realEstateProject
    image: mysql/mysql-server
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "realEstateProject"
    ports:
      - "3400:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
